/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppArtistIdRouteImport } from './routes/_app/artist.$id'
import { Route as AppLibraryRadioRouteImport } from './routes/_app/library.radio'
import { Route as AppPlaylistYtidRouteImport } from './routes/_app/playlist.$ytid'
import { Route as AppLibrarySongsKindRouteImport } from './routes/_app/library.songs.$kind'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppArtistIdRoute = AppArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRadioRoute = AppLibraryRadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppPlaylistYtidRoute = AppPlaylistYtidRouteImport.update({
  id: '/playlist/$ytid',
  path: '/playlist/$ytid',
  getParentRoute: () => AppRoute,
} as any)
const AppLibrarySongsKindRoute = AppLibrarySongsKindRouteImport.update({
  id: '/songs/$kind',
  path: '/songs/$kind',
  getParentRoute: () => AppLibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AppAboutRoute
  '/library': typeof AppLibraryRouteWithChildren
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/artist/$id': typeof AppArtistIdRoute
  '/library/radio': typeof AppLibraryRadioRoute
  '/playlist/$ytid': typeof AppPlaylistYtidRoute
  '/library/songs/$kind': typeof AppLibrarySongsKindRoute
}
export interface FileRoutesByTo {
  '/about': typeof AppAboutRoute
  '/library': typeof AppLibraryRouteWithChildren
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/artist/$id': typeof AppArtistIdRoute
  '/library/radio': typeof AppLibraryRadioRoute
  '/playlist/$ytid': typeof AppPlaylistYtidRoute
  '/library/songs/$kind': typeof AppLibrarySongsKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/library': typeof AppLibraryRouteWithChildren
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/artist/$id': typeof AppArtistIdRoute
  '/_app/library/radio': typeof AppLibraryRadioRoute
  '/_app/playlist/$ytid': typeof AppPlaylistYtidRoute
  '/_app/library/songs/$kind': typeof AppLibrarySongsKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/library'
    | '/search'
    | '/settings'
    | '/artist/$id'
    | '/library/radio'
    | '/playlist/$ytid'
    | '/library/songs/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/library'
    | '/search'
    | '/settings'
    | '/'
    | '/artist/$id'
    | '/library/radio'
    | '/playlist/$ytid'
    | '/library/songs/$kind'
  id:
    | '__root__'
    | '/_app'
    | '/_app/about'
    | '/_app/library'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/'
    | '/_app/artist/$id'
    | '/_app/library/radio'
    | '/_app/playlist/$ytid'
    | '/_app/library/songs/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artist/$id': {
      id: '/_app/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof AppArtistIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/radio': {
      id: '/_app/library/radio'
      path: '/radio'
      fullPath: '/library/radio'
      preLoaderRoute: typeof AppLibraryRadioRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/_app/playlist/$ytid': {
      id: '/_app/playlist/$ytid'
      path: '/playlist/$ytid'
      fullPath: '/playlist/$ytid'
      preLoaderRoute: typeof AppPlaylistYtidRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/songs/$kind': {
      id: '/_app/library/songs/$kind'
      path: '/songs/$kind'
      fullPath: '/library/songs/$kind'
      preLoaderRoute: typeof AppLibrarySongsKindRouteImport
      parentRoute: typeof AppLibraryRoute
    }
  }
}

interface AppLibraryRouteChildren {
  AppLibraryRadioRoute: typeof AppLibraryRadioRoute
  AppLibrarySongsKindRoute: typeof AppLibrarySongsKindRoute
}

const AppLibraryRouteChildren: AppLibraryRouteChildren = {
  AppLibraryRadioRoute: AppLibraryRadioRoute,
  AppLibrarySongsKindRoute: AppLibrarySongsKindRoute,
}

const AppLibraryRouteWithChildren = AppLibraryRoute._addFileChildren(
  AppLibraryRouteChildren,
)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppLibraryRoute: typeof AppLibraryRouteWithChildren
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppArtistIdRoute: typeof AppArtistIdRoute
  AppPlaylistYtidRoute: typeof AppPlaylistYtidRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppLibraryRoute: AppLibraryRouteWithChildren,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppArtistIdRoute: AppArtistIdRoute,
  AppPlaylistYtidRoute: AppPlaylistYtidRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
